name: build-target-firmware-alpine

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build binary
      run: |
        docker pull lvondaeniken/alpine-gcc-arm:latest
        docker run --rm --mount type=bind,source=.,target=/app lvondaeniken/alpine-gcc-arm ./app/build.sh  

    - name: Archive binary
      uses: actions/upload-artifact@v3
      with:
        name: nucleo-firmware-alpine
        path: |
          build/*.hex
          
