name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: lvondaeniken/ubuntu-arm-gcc:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build binary
      run: |
        cmake . -Bbuild -GNinja
        cmake --build build  

